### ISSUE TITLE
Add possibility to extend factory

### ISSUE THREAD

**Issue by stalniy** [aexmachina/factory-girl#109]
For example I have a `Subscription` model
```js
factory.define('Subscription', Subscription, {
  id: factory.seq('id'),
  price: 500,
  name: 'Pay for 1 month'
})
```

And want to define factory for `ExpiredSubscription` which extends `Subsription`.

The same feature is implemented in Ruby's factory_girl using nested factories.

**Comment by stalniy** [comment]
Meanwhile the only way to achieve this is to create a custom adapter. All good except that this adapter relies a bit on implementation details:

```js
const { factory, ObjectAdapter } = require('factory-girl');

class FactoryAdapter {
  constructor(adapter) {
    this.defaultAdapter = adapter
  }

  isFactory(Model) {
    return Model.constructor.name === 'Factory' || !!Model.initializer
  }

  build(Model, props) {
    return this.isFactory(Model)
      ? Model.build(this.defaultAdapter, props)
      : this.defaultAdapter.build(Model, props);
  }

  save(...args) {
    return this.defaultAdapter.save(...args);
  }

  destroy(...args) {
    return this.defaultAdapter.destroy(...args);
  }

  get(...args) {
    return this.defaultAdapter.get(...args);
  }

  set(...args) {
    return this.defaultAdapter.set(...args);
  }
}

factory.setAdapter(new FactoryAdapter(new ObjectAdapter()));

factory.define('User', Object, {
  id: factory.seq('id'),
  name: factory.chance('name')
});

factory.define('Admin', factory.getFactory('User'), {
  is_admin: true
});

factory.build('Admin')
  .then(console.log)
  .catch(console.error)
```

**Comment by stalniy** [comment]
alternatively it's possible to pass `factory` in adapter, so then implementation details will be hidden under `factory.build` method but I don't like the then we have a cyclic dependency `Adapter <-> FactoryGirl`. 

Both examples I put in gist: https://gist.github.com/stalniy/6ada2c890c55972abfcd400083e28d57

**Comment by stalniy** [comment]
So, do you guys think it make sense to add it as core feature?

**Comment by aexmachina** [comment]
I've added an `#extend` method in the `extend` branch. Would welcome your review/input on #113.

**Comment by aexmachina** [comment]
This has been released in v5 :tada:

**Comment by stalniy** [comment]
Great! Thanks!
