### ISSUE TITLE
Intercept cleanUp logic from adapter

### ISSUE THREAD

**Issue by stalniy** [aexmachina/factory-girl#110]
In SQL based system, there is such thing as foreign key constraints which doesn't allow to remove records if they are referenced in other tables. This may be fixed if `factory_girl` remove all created records in reversed order (the most top record will be removed first).

**Comment by stalniy** [comment]
Looks like it's not always the case... Because you can create record later and re-associate it with parent record.

So, for this case it looks like the best solution is to provide possibility/hook in adapter to override default `cleanUp` strategy

**Comment by aexmachina** [comment]
Hi, thanks for the issue. I'd suggest you configure foreign keys in the database so that the deletes cascade to the child records. Please feel free to reopen the issue if this isn't the solution in your case.

**Comment by stalniy** [comment]
foreign keys are configured and this is the issue actually :) If you have a profile and user tables and user has one profile, then database (at least MySQL) will not allow you to remove profile which is referenced by existing user (it throws an error saying this record is in use). But when you remove a user first, then profile can be removed successfully.

Anyway I guess there is no ideal solution for this situation. So, I'm fine to leave this closed

**Comment by aexmachina** [comment]
The ideal solution is to get the database to handle it. You can use ON DELETE CASCADE for this, see the MySQL docs https://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html
