### ISSUE TITLE
asyncPopulate and custom object types

### ISSUE THREAD

**Issue by stalniy** [aexmachina/factory-girl#111]
**Description**:
I my application I use [js-money]() package which allows to manage money easily. So, when I try to create a factory and `Money` object as factory attribute it returns me a plain object instead of `Money`

**Steps**
1. Define a factory
2. Invoke `factory.build` and pass in `balance` property `Money` instance
3. Output `result.balance.constructor`

**Actual result**
Shows `Object` and all `Money` methods are lost

**Expected result**:
Shows `Money`

**Reproduction code**:

```js
const { factory, ObjectAdapter } = require('factory-girl');
const Money = require('js-money');

factory.setAdapter(new ObjectAdapter());

factory.define('Account', Object, {
  name: factory.seq('name'),
  balance: new Money(10, Money.USD)
});

async function run() {
  const account = await factory.build('Account');
  console.log(account.balance.constructor);
}

run();
```

**Workaround**:

The workaround is to use a function for custom object types:

```js
factory.define('Account', Object, {
  name: factory.seq('name'),
  balance: () => new Money(10, Money.USD)
});
```

But this increases boilerplate and may become an issue when you want to pass result of one factory as properties into another factory.

**Possible solution**:
1. Copy only plain objects, constructor of which is `Object`
2. Allow to pass an option/hook in `FactoryGirl` class that makes a decision which objects may be copied

**Comment by stalniy** [comment]
@aexmachina @chetanism what do you think guys? I may create a PR but want to understand which way you would like this stuff to go

**Comment by stalniy** [comment]
Alternative way is to define an array of fields which shouldn't be copied 

```js
factory.define('Account', Object, {
  balance: new Money(500, Money.USD)
}, {
  perceiveAsPrimitive: ['balance']
})
```

Or allow to define object types which shouldn't be copy on `FactoryGirl` level (internally this may be a `Set`):

```js
factory.perceiveAsPrimitive([
   Money,
   ObjectId,
   SomeCustomObjectType
]);
```

**Comment by aexmachina** [comment]
That's not a workaround, that's _the way_ ;) That solution is simple, effective and extensible, and it's consistent with the style of this package.

**Comment by stalniy** [comment]
The issue is that I'm using one factory (with object adapter) which builds instance and passes parameters into another factory. So, the first time my function was unwrapped by first call and the another factory build receives plain arguments. This my money object become a regular object....

**Comment by stalniy** [comment]
this may seem nutural for factory definition but it doesn't work as expected during `create` or `build`. So, 

```js
const account = await factory.build('Account', { balance: new Money() })

console.log(account.balance.constructor) // Object
```
So, I think this is a bug

**Comment by stalniy** [comment]
Could you please reopen? 

From the source code I can definetely say that there is inconsistency in this mechanism because `asyncPopulate` doesn't perceive `bson` types to be an object but all other custom types are recursively iterated what makes object to loose its `Type` .

**Comment by stalniy** [comment]
By the way, the issue exists for `Date` object:

```js
const { factory, ObjectAdapter } = require('factory-girl');
const Money = require('js-money');

factory.setAdapter(new ObjectAdapter());

factory.define('Account', Object, {
  name: factory.seq('name')
});

function run() {
  factory.build('Account', { createdAt: new Date() })
    .then(account => console.log(account.createdAt.constructor)); // prints Object
}

run();
```

**Comment by Todmy** [comment]
I had the same problem on my previous project. So we spent some time to make it work with dirty hacks. Completely agree with @stalniy

**Comment by stalniy** [comment]
Currently I'm using a custom adapter and wrap all non-`Object` instance in function
```js
    wrapCustomTypes(props) {
        // TOOD: remove this method when the fix is agreed in https://github.com/aexmachina/factory-girl/issues/111
        return Object.keys(props).reduce((wrappedProps, name) => {
            const value = props[name];

            if (value && typeof value === 'object' && value.constructor !== Object) {
                wrappedProps[name] = () => value;
            } else {
                wrappedProps[name] = value;
            }

            return wrappedProps;
        }, {});
    }
```

**Comment by aexmachina** [comment]
I've pushed v5.0.0-beta.1 that doesn't traverse into objects unless they're instances of Object, so Dates and other types are preserved. Please give this version a go and let me know if this causes any other issues. It's a breaking change, but a few people have encountered issues with this, and I think this behaviour is less unexpected.

**Comment by stalniy** [comment]
Cool! Will give a try now

**Comment by stalniy** [comment]
All tests passed successfully without workaround. So, may be considered to be fixed :)

The only thing is that package.json in  v5.0.0-beta.1 points to `src/index.js` which uses ES6 import/export which are currently not supported in Nodejs envs. Guess it should be `dist/index.js`

**Comment by aexmachina** [comment]
That's good, thanks. Nothing's changed with the `main` property of the package.json. Okay I'll let people use the beta for a while before pushing v5.

**Comment by oliviertassinari** [comment]
I have been upgrading our test suite to `v5.0.0-beta.1` in order to fix the date issue. It's working great 👍.
