### ISSUE TITLE
Model-less Factory Girl Definitions

### ISSUE THREAD

**Issue by toszter** [aexmachina/factory-girl#112]
How do we go about creating and using definitions `factory-girl` without proper Models?

You can simply use Object as the model and the ObjectAdapter, which is the default adapter.

```
factory.define('test', Object, {})
factory.build('test').then(console.log) // => {}
```

**Comment by aexmachina** [comment]
You can simply use Object as the model and the ObjectAdapter, which is the default adapter.

```
factory.define('test', Object, {})
factory.build('test').then(console.log) // => {}
```
