### ISSUE TITLE
How to correctly create one-to-many associations?

### ISSUE THREAD

**Issue by swist** [aexmachina/factory-girl#114]
I am using `sequelize-typescript` and the sequelize adapter that ships with `factory-girl`.

I am trying to create a record with many items via one to many relationship (as defined with sequelizes `belongsTo` and `hasMany` APIs), but the following test scenario fails.

Can anyone point me to what I am possibly doing wrong? This is all written in typescript:

```typescript
import { factory, SequelizeAdapter } from 'factory-girl';
import { Image } from '../image';
import { ImageClassification } from '../imageClassification';

factory.setAdapter(new SequelizeAdapter());

factory.define('Image', Image, {
  id: faker.random.uuid,
  classifications: factory.assocMany('ImageClassification', 2)
});

factory.define('ImageClassification', ImageClassification, {
  id: faker.random.uuid,
  score: Math.random
});

describe('test setup', () => {
  it.only('should create associations via assocMany', async () => {
    const image = await factory.create('Image');
    // const images = await factory.createMany('Image', 5);
    console.log(image.classifications);
    expect(image.classifications).to.not.be.empty;
    // images.forEach((img) => expect(img.classifications).to.not.be.empty);
  });
})
```

**Comment by aexmachina** [comment]
Need more information. In what does it not fail? What does the console log above print? Maybe you need to use an accessor or a method to get the `classifications`? I'm not super familiar with Sequelize, but I suspect the problem's not in factory-girl.

**Comment by swist** [comment]
It fails always. Console log prints null. The generated sql statements create the related rows, but they d on't correctly set foreign keys. I am looking for the correct factory-girl api usage so that I can see if the problem is with the sequelize adapter and see about fixing it. I have tried other approaches (accessor/method) but the problem is with `create` or `createMany` not passing over the primary key of parent row to it's related neighbours

**Comment by bilby91** [comment]
@swist Hey, what defintions are you using for `factory-girl` ? I couldn't find them in DefinetlyTyped

**Comment by aexmachina** [comment]
Closing, feel free to reopen.
