### ISSUE TITLE
createMany with attrs param should not require number

### ISSUE THREAD

**Issue by createthis** [aexmachina/factory-girl#119]
Currently, I write my code like this when I want to override factory default values:
```javascript
      await factory.createMany('some_table', 3, [
        {id: 1, amount: 20.00, date: '2017-10-21'},
        {id: 2, amount: 21.00, date: '2017-10-22'},
        {id: 3, amount: 22.00, date: '2017-10-23'},
      ]);
```

If I delete a row and forget to change the number `3` to `2`, then I'll get a unique constraint error because factory-girl tries to insert two rows with id=1.

In this case it would make much more sense to auto detect the number of rows from the array and drop the number parameter:
```javascript
      await factory.createMany('some_table', [
        {id: 1, amount: 20.00, date: '2017-10-21'},
        {id: 2, amount: 21.00, date: '2017-10-22'},
        {id: 3, amount: 22.00, date: '2017-10-23'},
      ]);
```

**Comment by aexmachina** [comment]
Good point, have added support for that in v5.

**Comment by createthis** [comment]
Wow, upgraded. It just works! Totally awesome. Thanks!
