### ISSUE TITLE
How to use a factory definition in a separate file?

### ISSUE THREAD

**Issue by FelixFortis** [aexmachina/factory-girl#151]
Hi, JS newbie here. Hopefully a quick one for one of the old maintainers or anyone else taking a look.

All of the examples are both `define`ing and `build`ing factories in the same file. How do I export my factory definitions so that I can require/use them in a separate test file?

**Comment by Juice10** [comment]
If you are using [babel](https://babeljs.io) you can use this example:

One file with all of your factories: `test/factories.js`
```javascript
import { factory } from 'factory-girl';

factory.define('user', Object, {
  name: 'sam'
});

export default factory;
```

And in your tests: eg. `test/test.js`
```javascript
import factory from './factories';

factory.build('user').then()
```
