### ISSUE TITLE
Bookshelf Example?

### ISSUE THREAD

**Issue by jamesdixon** [aexmachina/factory-girl#16]
Hi,

First, thanks for opening up the issues section. This probably isn't an issue at all, but something on my end. When using `factory.build()`, nothing seems to be saved to my database. I'm using Bookshelf; here's my code:

```javascript
var factory = require('factory-girl'),
  BookshelfAdapter = require('factory-girl-bookshelf'),
  User = require('./models/user'),
  faker = require('faker');

var modelFactory = new factory.Factory();
modelFactory.setAdapter(BookshelfAdapter);

// define a factory using define()
factory.define('user', User, {
  firstName: faker.name.firstName(),
  lastName: faker.name.lastName(),
  email: faker.internet.email(),
  password: 'q1w2e3r4',
  active: false
});

factory.build('user', function(error, user) {
  console.log(user);
});
```

The object that's returned looks like this:

```javascript
{ attributes: {},
  _previousAttributes: {},
  changed: {},
  relations: {},
  cid: 'c4',
  _events: { saving: [Function] },
  firstName: 'Tyree',
  lastName: 'Sporer',
  email: 'Victoria.Waters31@gmail.com',
  password: 'q1w2e3r4',
  active: true }
```

All that said, my question is whether I'm using this properly with Bookshelf? I'm not sure if `factory.build()` calls `save()` or `forge()` in Bookshelf or if I need to do that on my own.

Thanks for your hard work on this module.

Best,
James

**Comment by aexmachina** [comment]
Yeah, the problem is that you're registering the adapter on a different factory instance. You want to use [this usage](https://www.npmjs.com/package/factory-girl-bookshelf). Let me know if that doesn't work.

**Comment by aexmachina** [comment]
I've improved the docs to make this clearer.

**Comment by jamesdixon** [comment]
Thanks @aexmachina. 

I made that change and also changed `factory.build()` to 'factory.create()', which saves the model as it should. Thank you for your help!
