### ISSUE TITLE
inheritance and traits?

### ISSUE THREAD

**Issue by mlennie** [aexmachina/factory-girl#17]
Hello thank you and great job! I remember with rails we could use inheritance and traits to specify objects with more specific attributes. Is there an equivalence here or do you suggest an alternative implementation? Thank You

**Comment by aexmachina** [comment]
Not sure... can you provide a concrete example or two?

**Comment by mlennie** [comment]
sure 
http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Inheritance
http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Traits

**Comment by aexmachina** [comment]
I'm open to this, but sceptical that it will be valuable enough to warrant the API changes that will be required. Feel free to suggest and API for it and we can work out the best way forward.

**Comment by ejlangev** [comment]
I'm going to explore implementing traits and see how big the API changes would need to be.  Will put up a PR and can go from there.  Traits are very useful though.

**Comment by aexmachina** [comment]
Okay sounds great.​

**Comment by karsep5** [comment]
@ejlangev Was there any progress on this front?

**Comment by RedMage** [comment]
I would be willing to look into this. Possibly something like using an extend option in the options hash. EG:

```javascript
FactoryGirl.define('basic-job', Job, {
  id: FactoryGirl.sequence(),
  title: 'pleb',
  hours: 8,
 daysPerWeek: 5
});

FactoryGirl.define('gruelling-job', Job, {
  daysPerWeek: 7
},{
  extends: 'basic-job'
});

let basicJob = FactoryGirl.buildSync('basic-job');
console.log(basicJob.id) //   1
let gruellingJob = FactoryGirl.buildSync('gruelling-job');
console.log(gruellingJob.id, ',', gruellingJob.hours, ',', gruellingJob.daysPerWeek); // 2,8,7
```

**Comment by aexmachina** [comment]
Yep, that sounds good to me.

**Comment by chetanism** [comment]
I see that @RedMage has already raised a PR to address this issue as per the above suggested approach. I have another approach to suggest!
This approach would change the API, but it would let users handle any complex scenario they want, the way they want! It should still be possible to avoid breaking the axisting API.


We can modify the factory.define API to allow passing a function that returns the attribute object to be used. So, it would be possible to define a factory as:

```javascript
factory.define('User', User, function (buildOptions) {
	var attrs = {
		username: factory.sequence(function (n) { return 'username_' + n; }),
		password: 'dummy_password',
		confirmed: false,
		mobileVefirfied: false,
		mobileNumber: ''
	};

	if(buildOptions.confirmed) {
		attrs.confirmed = true;
	}

	if(buildOptions.mobileVerified) {
		attrs.mobileNumber = factory.sequence(function (n) { return '12345' + n; })
		attrs.mobileVerified = true;
	}

	// ... and so on

	return attrs;
});
```

The buildOptions can be specified while creating/building models:

```javascript
factory.create('User', { username: 'custom_username' }, { confirmed: true, mobileVerified: true });
```

The clear benefit here is that we can apply several `traits` simultaneously, which would be problematic in the `extends` approach suggested by @RedMage.


If it sounds good, I can spin up a PR to make the change!

**Comment by aexmachina** [comment]
Yes I agree. As per usual is JavaScript, plain old functions are best! Higher order functions for traits is a good solution too. Good thinking!

**Comment by chetanism** [comment]
In the long run I think es6 classes would probably lets us handle all this seamlessly. For now I think this should make life easier for everyone!

I'll raise a PR soon with these suggested changes!

@RedMage, sorry to hack up your efforts, I just need this in my project very soon, I hope this should handle your scenarios as well. Will be glad to have you as well to review the PR once I raise it.

**Comment by RedMage** [comment]
@chetanism  That's fine. I, too, want something like this in a project 'very soon'. Nobody was doing anything, so I tapped into the old American pioneer spirit.

However, if my little bit of gumption there inspired you to do something even grander, then I am pleased. That's what the spirit of Individualism combined with the Protestant work ethic is _supposed_ to do.

I will close my pull request.

**Comment by chetanism** [comment]
I just raised #49, please review it.
While I was there, I have cleaned up the tests a little.
Still TODO items:
1] buildMany/createMany APIs don't support the buildOptions parameter yet. The APIs are already complicated and I didn't want to make it more confusing than useful, unless we have some sort of consensus on the API.
2] Documentation needs to be updated.

**Comment by chetanism** [comment]
Updated #49 to include documentation as well as support for buildMany, createMany, assoc, assocBuild, assocMany, assocBuildMany.

Please try it out with any existing projects as well to ensure nothing breaks!

**Comment by aexmachina** [comment]
Yeah maybe this should be 4.0-beta?

**Comment by chetanism** [comment]
Sounds good to me.

**Comment by chetanism** [comment]
Just having a thought that if #49 changes don't break any existing API, we can have a minor release. For v4, we can then plan out what exactly we want to achieve and plan for it accordingly. At the same time, to be on safer side, we'll need a confirmation from few users that the changes indeed don't break their code!

**Comment by aexmachina** [comment]
Closing this now because v4 provides great solutions for this, and is available in beta now.
