### ISSUE TITLE
Associations on bookshelf models. 

### ISSUE THREAD

**Issue by b3njamin** [aexmachina/factory-girl#18]
Any way we can get these to work?

**Comment by aexmachina** [comment]
Doesn't it already work?

**Comment by aexmachina** [comment]
Maybe provide an example

**Comment by b3njamin** [comment]
Sorry, one to one relationships work doesn't seem to handle one to many. 

```js
factory.define('variant', Variant, {
  'quantity': function () {
    return faker.random.number(1, 10)
  },
  'colour': function () {
    return factory.assoc('colour', 'product_colour_id'),
   }
  'size': function () {
    factory.assoc('size', 'product_size_id')
  }
})

```

**Comment by aexmachina** [comment]
That should be:

```js
factory.define('variant', Variant, {
  'quantity': faker.random.number.bind(faker, 1, 10)
  'colour': factory.assoc('colour', 'product_colour_id'),
  'size': factory.assoc('size', 'product_size_id')
});
```

**Comment by b3njamin** [comment]
Its trying to set the a colour column and size column on the variant table, rather then product_colour_id & product_size_id columns?

**Comment by aexmachina** [comment]
Right, you should omit the second parameter in the call to `.assoc()`, then it will return the object and Bookshelf should be happy.

```
factory.define('variant', Variant, {
  quantity: faker.random.number.bind(faker, 1, 10)
  colour: factory.assoc('colour'),
  size: factory.assoc('size')
});
```

**Comment by b3njamin** [comment]
It tries to insert it as an object, 

```
TypeError: insert into `variants` (`colour`, `created_at`, `quantity`, `size`, `updated_at`) values ('{\"colour\":\"ivory\",\"swatch\":\"000000\",\"updated_at\":\"2015-08-17T01:15:36.442Z\",\"created_at\":\"2015-08-17T01:15:36.442Z\",\"id\":16}', '2015-08-17 01:15:36.809', 0, '{\"size\":\"XL\",\"updated_at\":\"2015-08-17T01:15:36.553Z\",\"created_at\":\"2015-08-17T01:15:36.553Z\",\"id\":16}', '2015-08-17 01:15:36.809') - undefined is not a function
```

**Comment by aexmachina** [comment]
Right okay, you need to use `factory.assoc('colour', 'id')`. I've updated the README and added a test for this. Let me know if that doesn't work for you.

**Comment by b3njamin** [comment]
Yeah sorry was just confusing that its actually using the id rather then the asociation_name. Any way to support the association name, rather then name_id also any way to support association types, hasOne etc, perhaps using some sort of reflection? This would make it super easy to use with bookshelf.

**Comment by aexmachina** [comment]
The adapter layer is pretty simple, so that's not supported at this stage. I'm open to pull requests though if that's of value to you.
