### ISSUE TITLE
Issues on introduction to project

### ISSUE THREAD

**Issue by garmoshka-mo** [aexmachina/factory-girl#21]
It is great project, this is very cool that it has so many abilities,
though common use of factories usually is simple, like:

````
factory.define('post', Post, {
    title: 'Втащили по клюву!',
    rate: 2
});
````

And when you look at readme - it looks overcomplicated
I think, many people may stop at this point and then try to look for alternatives.

It would be more friendly to have first example simple - to show, that it is really proper tool for factories.
(Programmer would use ORM itself for populating database, if he wouldn't look for simplicity)

Like here - first example shows only essentials: https://mochajs.org/
And reader understands - that's easy tool for testing.

**Comment by aexmachina** [comment]
That's a good suggestion, that README has really just grown over time and lost its simplicity.

**Comment by aexmachina** [comment]
I've updated the README, is that clearer?

**Comment by garmoshka-mo** [comment]
https://github.com/aexmachina/factory-girl#defining-factories

In my opinion it is still tries to give too much information, than needed to visitor, 
who looks something to quickly add records to his tables.

Usually he won't need all these features, so they could be moved to following section with name like "Advanced"
And first "Simple" section could be just like 

````
var factory = require('factory-girl');
var User    = require('../models/user');

factory.define('user', User, {
  username: "Bob",
  scores: 50,
});

factory.build('user', function(err, user) {
  console.log(user.attributes);
  // => {username: 'Bob', scores: 50}
});
````

Also too much comments usually mean, that code is not clear itself.
Variable/function names - is best tool to express what code does as [uncle bob](https://www.google.com.ua/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#es_th=1&q=uncle%20bob) says

**Comment by aexmachina** [comment]
Cool thanks for the feedback. I've made a few more changes. Any other improvements feel free to submit a PR.

**Comment by mikeerickson** [comment]
@aexmachina Sorry for being a newb here, but what is expected when requiring the 'User' model?  Try to use with an empty Node project

var User    = require('../models/user');

What does this object expect?

Is there an example project that I could review for details?

Don't want to toss it away due to lack of documentation, etc. but not much information supplied for a brand new app.

**Comment by mikeerickson** [comment]
@aexmachina If you could supply a sample of user model at a minimum, I can surely take it from there

**Comment by aexmachina** [comment]
@mikeerickson it depends on [the adapter](https://github.com/aexmachina/factory-girl#adapters) you're using. e.g. If you're [using Mongoose](https://www.npmjs.com/package/factory-girl-mongoose) then the user model would be a Mongoose model, or if you're [using Bookshelf](https://www.npmjs.com/package/factory-girl-bookshelf) then the user model would be a Bookshelf model.

**Comment by mikeerickson** [comment]
@aexmachina That makes good sense, but what if you arent using either (just plain vanilla JS)  is there an adapter for such a beast?  I am just wanting to create temporary objects for mocha tests.

**Comment by aexmachina** [comment]
Yes, it's the `ObjectAdapter`. It uses `var post = new Post()`, `post.save()` and `post.destroy()`.

```js
var Post = function() {};
Post.prototype.save = function() {};
Post.prototype.destroy = function() {};

factory.define('post', Post);
factory.setAdapter(new factory.ObjectAdapter(), 'post');
```

**Comment by bogdan-calapod** [comment]
@aexmachina - A bit late to the party, but I do think that this example should be placed in the readme somewhere - I've been looking for quite a while around here debugging `model.save is not a function` trying to use this with `objectmodel`.

**Comment by aexmachina** [comment]
Okay, thanks for the reminder. Have done.
