### ISSUE TITLE
including/omitting specific properties

### ISSUE THREAD

**Issue by jamesdixon** [aexmachina/factory-girl#22]
Hi again,

Wanted to see what your thoughts were on having the option to either include or omit specific properties from the factory? For example, if I wanted to do a partial update of a `person` object rather than all the fields, I may only want a subset of the available properties. I was thinking something like:

```javascript
factory.build('user', { omit: [ 'email', 'password'] }, function(err, user) {
    // all properties returned except email and password
    console.log(user.attributes);
});
```
Best,
James

**Comment by aexmachina** [comment]
I'd just use lodash's `pick` or `omit` functions. Keep each tool focused on doing one thing well.

```javascript
factory.build('user', function(err, user) {
    console.log(_.omit(user.attributes, ['email', 'password']));
});
```

**Comment by jamesdixon** [comment]
Fair enough. Thanks!
