### ISSUE TITLE
afterCreate and buildMany

### ISSUE THREAD

**Issue by siboulet** [aexmachina/factory-girl#25]
Hi,

I discovered the afterCreate opiton while looking at the source code. It be great if the afterCreate option was documented in the README. This option is essential when using ex. passport-local-mongoose to set user password by calling setPassword() method before returning the created model.

Also, I noticed afterCreate is only called when using factory.create(), but not when using factory.createMany(). Is this expected behavior?

Thanks

**Comment by aexmachina** [comment]
Good point. I've added docs and support for `afterCreate` to `createMany()`

**Comment by siboulet** [comment]
@aexmachina thanks! Can you do a release with createMany() calling afterCreate callback?

**Comment by aexmachina** [comment]
Yes I already published v2.2.0 (but the git push failed).
