### ISSUE TITLE
What's the best way to go about making a factory for a SubDocument?

### ISSUE THREAD

**Issue by jmnsf** [aexmachina/factory-girl#26]
In this particular case, I'm using mongoose.

Say I have a document `Post` with embedded `Comment`s. I want to create specific comments through factories, but there isn't a Comment model from which I can base the factory.

Should I skip the adapter in this case and just use the schema in the factory declaration, or is there another way to do this?

**Comment by aexmachina** [comment]
You can probably do this using the [`afterCreate` hook](https://github.com/aexmachina/factory-girl#aftercreate-functioninstance-options-callback)

**Comment by jmnsf** [comment]
Where I use it is besides the point, the issue here is that I can't use a traditional factory because there isn't a DRM for the model in question. Can I just omit the parameter and do something like:

```
factory.build('subdoc', (err, doc) => {});
```

And not have any side effects due to the lack of a model?

**Comment by aexmachina** [comment]
Right, you should be able to use the [ObjectAdapter](https://github.com/aexmachina/factory-girl#adapters) to get around the fact that you don't have a model class.

**Comment by jmnsf** [comment]
So, according to the docs, something like this:

```
factory.define('post', { type: 'text' });
factory.setAdapter(factory.ObjectAdapter, 'post');
```

used like so: `factory.buildSync('post')` results in an error:

```
TypeError: adapter.build is not a function
  at builder.buildSync (node_modules/factory-girl/index.js:243:24)
  at null.buildSync (node_modules/factory-girl/index.js:38:32)
```

**Comment by aexmachina** [comment]
You want to use `new factory.ObjectAdapter()` :)

**Comment by aexmachina** [comment]
I'll fix the docs now :)

**Comment by jmnsf** [comment]
Thank you for the help ;)
