### ISSUE TITLE
`factory.assoc` doesn't work on nested properties / embeded 

### ISSUE THREAD

**Issue by codynguyen** [aexmachina/factory-girl#34]
Hi,

As the title says, `factory.assoc` doesn't work when placed inside a nested properties. For example:

```
// Model definitions
mongoose.model('Currency', new mongoose.Schema({
  _id: String, // e.g. 'cad'
  name: String, // e.g. 'Canadian Dollar'
}));
var Currency = mongoose.model('Currency');

mongoose.model('Asset', new mongoose.Schema({
  name: String,
  currency: {
    type: String,
    ref: 'Currency',
    required: true,
  },
}));
var Asset = mongoose.model('Asset');

mongoose.model('User', new mongoose.Schema({
  name: String,
  assets: [ Asset.schema ],
  preferences: {
    currency: {
      type: String,
      ref: 'Currency',
      default: 'cad',
      autopopulate: true,
    },
  }
}));
var User = mongoose.model('User');

// Factory definitions
factory.define('currency', Currency, {
  _id: factory.sequence(function(n) { return 'cad' + n; }),
  sign: '$'
});

factory.define('user', User, {
  name: 'Test',
  // embeded object
  assets: [{
    type: 'other_asset',
    currency: factory.assoc('currency', '_id'), // Fails
    currency_value: 1.01,
    group: 'test',
  }],
  // nested properties
  preferences: {
    currency: factory.assoc('currency', '_id'), // Fails
  },
});

// This would fails
factory.create('user', function(err, user) { console.log(err, user) });
```

I know we have `afterCreate`, however we could never get to that point because of `required: true` validation in the embeded `Asset`.

 `afterBuild` wouldn't work either, because the `factory.assoc('currency', '_id')` part is never called and considered a string (instead of a callback) when saving. Even if there's no such `required: true` validation, the object still won't save because it just isn't the valid data type.

I think the problem comes from `asyncForEach` here (https://github.com/aexmachina/factory-girl/blob/master/index.js#L200) doesn't go any deeper past 1st-level attribute keys. Maybe we can wrap the function in another recursive function?

**Comment by aexmachina** [comment]
It looks fairly simple to add another branch to `asyncForEach` to recurse into the passed `attrs`. My only concern with this is that there's probably users who are relying on the non-recursing behaviour. If this was a solution to your problem then we could consider doing this and bumping the major version.

**Comment by damionvega** [comment]
It would be helpful to have sequence available also.

```js
Factory.define('account', Account, {
  num: Factory.sequence(),
  name: {
    first: 'user',
    last: Factory.seq(n => `user${n}`), // Returns the function
  },
  email: Factory.seq(n => `user${n}@site.com`),
})
```

**Comment by aexmachina** [comment]
This will be available in v4, which will be available as a beta version very soon!
