### ISSUE TITLE
What type of models does this require?

### ISSUE THREAD

**Issue by axelson** [aexmachina/factory-girl#38]
We don't have any actual models in our code right now, just plain javascript objects that are returned as json from a REST API. Can we still use factory-girl? I don't see anything in the docs about what methods the models need to support.

**Comment by aexmachina** [comment]
Yup, you can use the [ObjectAdapter](https://github.com/aexmachina/factory-girl#objectadapter). I've just added a section to the readme about this.

**Comment by axelson** [comment]
Cool, thanks!
