### ISSUE TITLE
Build with dependencies

### ISSUE THREAD

**Issue by exoszajzbuk** [aexmachina/factory-girl#39]
I'd like to use `factory-girl` in a project which cannot use `npm` for dependency management.

As a new feature, could you include Grunt/Gulp build script to create a standalone .js file including dependencies e.g. into `dist/factory-girl.js` and `dist/factory-girl.min.js`

**Comment by aexmachina** [comment]
The module can already be used without CommonJS modules. AMD is supported, or `Factory` and `ObjectAdapter` will be attached to `window`.
