### ISSUE TITLE
How to create many-to-many associations with Bookshelf?

### ISSUE THREAD

**Issue by vitorbaptista** [aexmachina/factory-girl#43]
Hi,

I'm sorry if GitHub Issues isn't the right place to ask these questions. I'd be happy to re-ask them in StackOverflow if needed.

Considering the many-to-many association example in bookshelfjs.org:

``` javascript
var Book = bookshelf.Model.extend({
  tableName: 'books',
  authors: function() {
    return this.belongsToMany(Author);
  }
});

var Author = bookshelf.Model.extend({
  tableName: 'authors',
  books: function() {
    return this.belongsToMany(Book);
  }
});
```

This needs a `books` and `authors` table, and also an association table `authors_books`. I tried using `authors: factory.assocMany('author', 'id', 2)` in the Book factory, but it ended up trying to insert an `authors` column in the DB. Are these kind of associations supported? If not, is there any workaround?

**Comment by aexmachina** [comment]
It's been a while but I believe that these methods return an array, which I thought was supported by Bookshelf. It's not covered in the test suite for factory-girl-bookshelf. Do you feel like adding a test for this?

**Comment by vitorbaptista** [comment]
I'd be happy to add a test for this, but it'll be failing. I'm not sure if that's the correct way of doing this as well, or if this is supported by factory-girl as is at all.

**Comment by aexmachina** [comment]
Awesome, thanks! factory-girl is only responsible for creating an array of objects, and it's up to the adapter to work out how to present that to the model. So the PR would be to factory-girl-bookshelf.

I would then look at adding the new createMany tests into the standard suite of tests that are used by all of the other adapters.

**Comment by b3njamin** [comment]
@vitorbaptista Just FYI - bookshelf doesn't handle saving arrays, as hasMany - it looks like it could be implemented however I usually create my owner record then create my child records there after.

**Comment by aexmachina** [comment]
factory-girl v4 (currently available as a beta) now includes the BookshelfAdapter. I'd be open to anyone having a go at investigating the best way to support this. Is this something anyone here would be interested in?

My recollection was that this was supported by Bookshelf, but it's been a while since I've used it.
