### ISSUE TITLE
Should Factory.build() create associated objects? 

### ISSUE THREAD

**Issue by SeanDunford** [aexmachina/factory-girl#48]
Is it expected behavior for factory-girl to create (save to db) associated objects when you call .build on a factory? If I'm calling .build I'm not expecting any docs to be saved to the database.  

Reproduce code
```javascript
var factory = require('factory-girl');
var db = require('myDbConnection');
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var ObjectId = Schema.Types.ObjectId;

var userSchema = new Schema({
    post: {type: ObjectId, ref: 'user'}
});

var postSchema = new Schema({
    text: {type: String}
});

var UserModel = db('test').model('user', userSchema);
var PostModel = db('test').model('post', postSchema)

factory.define('user', UserModel, {
    post: factory.assoc('post', '_id')
});

factory.define('post', PostModel, {
    text: 'Hello.'
});

factory.build('user', {}, function(err, user){
    if(err) throw err;
    console.log('user: ', user);  
});
```

After the callback is executed user is a valid doc and has a valid _id but isn't saved to the db. Yet, Post was saved to the db. I would expect both to be non-saved models.

**Comment by aexmachina** [comment]
Yes, that is expected behaviour, but I agree that it is somewhat unexpected. I'd welcome a PR that fixes this!

`#assoc` is designed to return an `id`, which in many cases wouldn't be generated until it's inserted into the database.

**Comment by aexmachina** [comment]
In fact there's a stale PR for this already: #19

**Comment by aexmachina** [comment]
It's not ideal, but #50 adds an `assocBuild` method that always calls `build` on the associated records.

**Comment by SeanDunford** [comment]
Beautiful, thank you. Thanks for turning that around so fast.
