### ISSUE TITLE
Circular Associations

### ISSUE THREAD

**Issue by emckay** [aexmachina/factory-girl#69]
I am trying to use factory-girl v4 (with the Sequelize adapter).

I have a `User` model that belongs to an `Organization` model, and I would like to have the `Organization` factory create an associated `User` and have the `User` factory create an associated organization.

When I try to do this using `factory.assoc`, I get an infinite loop as I assume the `User` and `Organization` factories are calling each other repeatedly.

Here's a sample of the code that I've tried:

``` js
factory.define('User', User, {
  // ...
  OrganizationId: factory.assoc('Organization', id),
})

factory.define('Organization', Organization, {
  // ...
  User: factory.assoc('User'),
})
```

Is this behavior supported by factory-girl, or can the associations only go one way? I could not find much documentation for the `assoc` function, so apologies in advance if there is something obvious I'm missing.

Thanks!

**Comment by chetanism** [comment]
Hi @emckay, sorry for a late response.
Yes, factory-girl doesn't support circular dependencies as of now.
Following are a couple of hacks that may help you to get going:

```javascript
function User() {}
function Organization() {}

Factory.define('User', User, {
  OrganizationId: undefined,
});

Factory.define('Organization', Organization, {
  id: Factory.sequence('org_id'),
  User: Factory.assoc('User'),
});

describe.only('circular dependency', function () {
  it('builds models', asyncFunction(async function () {
    const o = await Factory.build('Organization');
    o.User.OrganizationId = o.id;
  }));
});
```

```javascript
function User() {}
function Organization() {}

Factory.define('User', User, {
  OrganizationId: undefined,
});

Factory.define('Organization', Organization, {
  id: Factory.sequence('org_id'),
  User: Factory.assoc('User'),
}, {
  afterBuild: model => {
    model.User.OrganizationId = model.id;
    return model;
  },
});

describe.only('circular dependency', function () {
  it('builds models', asyncFunction(async function () {
    const o = await Factory.build('Organization');
  }));
});
```

We'll try to have something to handle circular dependency, in case you have a suggestion, please submit a PR and we'll try to get it merged asap.

Thanks!

**Comment by emckay** [comment]
Thanks for the help! I have been working around this by using buildOptions to decide whether to build any associations in the afterBuild and afterCreate hooks.

For example `factory.create('User', { }, { withOrganization: true })` will create a User with an associated Organization and `factory.create('Organization, { }, { withUser: true })` will create an Organization with an associated User. The factories have a little bit of extra boilerplate, but it's not too bad.
