### ISSUE TITLE
Duplicating assigned attributes

### ISSUE THREAD

**Issue by jonatanklosko** [aexmachina/factory-girl#72]
Consider the following factory:
```javascript
const User = require('models/user');

factory.define('user', User, {
  username: factory.sequence(n => `sherlock_${n}`),
  name: "Sherlock Holmes",
  password: "Password",
  passwordConfirmation: function() { return this.password; }
});
```
I'd expect the following to pass.
```javascript
factory.build('user', { password: 'secret' })
  .then(user => expect(user.passwordConfirmation).to.equal('secret');
```
The syntax could differ but I think it's common use case to duplicate (or do something else) on an already assigned attribute.

**Comment by chetanism** [comment]
Hi @jonatanklosko,
You can try following to achieve the same effect:

```javascript
Factory.define('user', User, {
  username: Factory.sequence(n => `sherlock_${n}`),
  name: 'Sherlock Holmes',
  password: 'password',
  passwordConfirmation: undefined,
}, {
  afterBuild: model => {
    model.passwordConfirmation = model.password;
    return model;
  },
});
```

**Comment by jonatanklosko** [comment]
Hey @chetanism,
I've already tried this and actually it should be
```javascript
afterBuild: model => {
  model.passwordConfirmation = model.passwordConfirmation || model.password;
  return model;
},
```
The problem with this solution is that `afterBuild` is not invoked when you use `create`.

I can think of a feature, that would allow us to do:
```javascript
/* ... */
password: "secret",
passwordConfirmation: factory.duplicate('password')
/* ... */

/* Or even more flexible */

/* ... */
password: "secret",
passwordConfirmation: factory.after('password', password => /* do something and return */)
/* ... */
```
This way you can evaluate all *normal* attributes and those `duplicate`/`after` calls at the end.
What are your thoughts =) ?

**Comment by aexmachina** [comment]
@chetanism I think maybe we should consider calling both `afterBuild` and `afterCreate` when creating. I think this makes sense because `create` does follow `build`.

**Comment by chetanism** [comment]
@jonatanklosko, sorry for a long delay!
I have raised #73 as per @aexmachina 's suggestion. The `afterBuild` callback should now be invoked on `create` calls as well (once the PR gets merged :)).

**Comment by jonatanklosko** [comment]
Yeah this behavior makes more sense. The PR looks great, thanks! =)

**Comment by aexmachina** [comment]
#73 has been merged, closing this issue now. Please advise if there's any issues.

**Comment by jonatanklosko** [comment]
I've just realised that it's not invoked after `#attrs` as well.

**Comment by chetanism** [comment]
Hi @jonatanklosko, the order of execution for these methods is `attrs` -> `build` -> `create`. As of now, we just have callbacks for `afterBuild` and `afterCreate`, hence the callbacks are not executed for `attrs` call. I'll open another issue to have an `afterAttrs` callback.
