### ISSUE TITLE
v4 cleanUp() problems

### ISSUE THREAD

**Issue by createthis** [aexmachina/factory-girl#76]
Hello.

I'm using factory-girl 4.0.0-beta.7 with sequelize and mocha. I've noticed a few problems:
- the README.md still says `cleanup` as does the test, but the method was renamed to `cleanUp`.
- I'm getting this error when I run `cleanUp()`: `(node:30699) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 149): TypeError: model.destroy is not a function`
  
  That seems to be originating from the DefaultAdapter: https://github.com/aexmachina/factory-girl/blob/7e4335330a4e85d4c6c2ecf9a881df8ff9b77965/src/adapters/DefaultAdapter.js#L10

**Comment by chetanism** [comment]
Hi @createthis, we'll fix the doc.
Regarding your issue, afaik sequelize model instances have a `destroy` [method](http://docs.sequelizejs.com/en/latest/api/instance/#destroyoptions-promiseundefined).
Can you check what's the type of the model object.

**Comment by createthis** [comment]
When I print out `model` there via `console.log("model=",model);`, this is what I get:

```javascript
model= function () {
    Instance.apply(this, arguments);
  }
```

**Comment by createthis** [comment]
As a way to easily reproduce this issue, I made a quick example project: https://github.com/createthis/sequelize-factory-girl-v4-example

Just:
```bash
npm install
npm test
```

And you'll see the warning in the output:

>   factory
>     #cleanUp
>       ✓ should cleanUp without errors or warnings
> (node:27315) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: model.destroy is not a function
> 
> 
>   1 passing (79ms)

If you want to see the trace, just uncomment this `process.on` block and restart the test: https://github.com/createthis/sequelize-factory-girl-v4-example/blob/master/test_helpers/index.js#L19

**Comment by chetanism** [comment]
I have probably found the problem, will raise a PR after verifying!

**Comment by chetanism** [comment]
@createthis, I have raised #78 to fix the issue. Thanks for pointing out the issue and providing the sample project!

**Comment by createthis** [comment]
Confirmed fixed on my end using that code. 👍

**Comment by b3njamin** [comment]
@aexmachina would be cool to get a beta release with all the latest fixes.

**Comment by cbrwizard** [comment]
Still having this error with Mongoose

**Comment by aexmachina** [comment]
I thought this issue was already resolved. Sounds like you're having a problem with running tests in parallel, which is a different issue. `cleanUp` assumes serial operation. In order to support parallel you'll need to have a different `FactoryGirl` instance for each parallel process.
