### ISSUE TITLE
Many to Many with Sequelize

### ISSUE THREAD

**Issue by santomegonzalo** [aexmachina/factory-girl#81]
Hello... factory-girl works perfect but now I have a case where I have many-to-many on sequelize and I want to know how possible could be to send extra options into `.build` function so the adapters could use that... for example on sequelize if we have `belongsToMany` we could send the option

```javascript
return Model.build(props, {
  include: Job // Job is a sequelize model
}
``` 

what do you think? do you see it possible?

**Comment by chetanism** [comment]
Hi @santomegonzalo, I am not fluent with sequelize, but I suspect `#assoc`, `#assocMany` are the APIs that you are looking for.

For the example you gave, you should be able to do:
```javascript
factory.define('job', Job, { /* attributes */ });
factory.define('model', Model, {
  job: factory.assoc('job', '<job_id_field>'),
  /* rest of the attributes */
});

factory.create('model').then(model => {
  // model.job should have the id of a job object
})
```
