### ISSUE TITLE
How to reset sequence for v4?

### ISSUE THREAD

**Issue by koshuang** [aexmachina/factory-girl#83]
Hello All,

I need to reset sequence after running each test suite. Is it possible to do it for v4?

Thanks!

**Comment by koshuang** [comment]
#84 is the PR for reseting sequence. Would you mind taking a look?

**Comment by adek23** [comment]
@aexmachina Why did you close this PR?

**Comment by aexmachina** [comment]
That was a mistake. That PR has been merged now. Thanks!
