### ISSUE TITLE
REDUX ORM Adapter created

### ISSUE THREAD

**Issue by carlesnunez** [aexmachina/factory-girl#88]
Hello @aexmachina

I've been working with factory-girl with redux-orm and I'll would like to integrate the adapter with that awesome factory library.

I've made the tests and checked eslint style. We can discuss anything else if you like but this is working great for me on my actual project.

Here is the PR
https://github.com/aexmachina/factory-girl/pull/87

**Comment by aexmachina** [comment]
Closing in favour of #87
