### ISSUE TITLE
Sync version of build?

### ISSUE THREAD

**Issue by mltsy** [aexmachina/factory-girl#89]
Maybe this isn't the place for feature requests (let me know if there's a better place), and unfortunately I'm fairly new to Node and newer JS functions, so I don't have a PR for this, but:

It sure would be great to have a `.build_sync` function, or perhaps a `sync` flag for the `build` function.  I'm having a heck of a time awaiting the promise in my mocha test suite (my environment doesn't support `await`).  I know this was built at least partly to solve the problem of needing async factories (for performance, or whatever), but if adding a sync option isn't terribly difficult, this would certainly be the best sync factory library I have found so far.

**Comment by aexmachina** [comment]
The problem is that any of the attributes of the model may be asynchronous. You can return promises from your tests as well:

```js
it("returns the current_user", () => {
  return factory.build('Cloud')
    .then( cloud =>factory.build('User', {cloud_id: cloud.id}) )
    .then( current_user => {
      expect(...).to.equal(current_user.id)
      expect(...).to.equal(cloud.id)
    });
  });
});
```

**Comment by mltsy** [comment]
Well that's easy to solve: if I pass in a Promise to one of the attributes, I should expect to get that attribute back as a Promise when calling `build_sync` :smile:

I mean, you're right.  There are alternate ways to organize the tests, but I still haven't found one that is as easy to maintain as just using sync factories.  For instance, in your example there, I'd have to repeat those factories for every test in that context.  Removing that redundancy, it would looks like the example I gave, which is also relatively elaborate.  And that's just the required trade-off when working with async behavior.  But when I don't *have* any async behavior, it's an unfortunate one.
