### ISSUE TITLE
v4.2.2 cleanUp() fail with children records

### ISSUE THREAD

**Issue by skwongr** [aexmachina/factory-girl#94]
Currently the cleanUp invokes `destroy` with the order that was created. When you have models with relationship like `Author` has many `Book`. You create an author and then some books with the created author, cleanUp() will try to destroy the author because it was created first but it will fail with foreign key constraint error since books are still referencing it (I'm using postgres btw and no cascade delete).
It would be nice the cleanUp invokes destroy in reverse order. Thanks!

**Comment by aexmachina** [comment]
This is not something that we would handle in factory-girl. Best way to handle this is in the underlying database. The adapter interface would need to be much more complex to handle this case.
